version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    # Core Bug Finders
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - bodyclose
    
    # Style & Formatting
    - revive
    
    # Security & Readability
    - gosec
    - goconst

output:
  sort-order:
    - file
    - linter
    - severity