// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package database

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (content)
VALUES ($1)
RETURNING id, content, created_at
`

func (q *Queries) CreateMessage(ctx context.Context, content string) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, content)
	var i Message
	err := row.Scan(&i.ID, &i.Content, &i.CreatedAt)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, content, created_at FROM messages
ORDER BY created_at DESC
`

func (q *Queries) ListMessages(ctx context.Context) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(&i.ID, &i.Content, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
